export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CALCULAR_FRETE_REQUEST = "CALCULAR_FRETE_REQUEST";
export const CALCULAR_FRETE_SUCCESS = "CALCULAR_FRETE_SUCCESS";
export const CALCULAR_FRETE_FAIL = "CALCULAR_FRETE_FAIL";
