export const WAREHOUSE_EDIT_REQUEST = "WAREHOUSE_EDIT_REQUEST";
export const WAREHOUSE_EDIT_SUCCESS = "WAREHOUSE_EDIT_SUCCESS";
export const WAREHOUSE_EDIT_FAIL = "WAREHOUSE_EDIT_FAIL";

export const WAREHOUSE_CREATE_REQUEST = "WAREHOUSE_CREATE_REQUEST";
export const WAREHOUSE_CREATE_SUCCESS = "WAREHOUSE_CREATE_SUCCESS";
export const WAREHOUSE_CREATE_FAIL = "WAREHOUSE_CREATE_FAIL";
export const WAREHOUSE_CREATE_RESET = "WAREHOUSE_CREATE_RESET";

export const WAREHOUSE_UPDATE_REQUEST = "WAREHOUSE_UPDATE_REQUEST";
export const WAREHOUSE_UPDATE_SUCCESS = "WAREHOUSE_UPDATE_SUCCESS";
export const WAREHOUSE_UPDATE_FAIL = "WAREHOUSE_UPDATE_FAIL";
export const WAREHOUSE_UPDATE_RESET = "WAREHOUSE_UPDATE_RESET";
